version: '3.8'

services:
  # 1. EL MONITOR (Motor principal)
  radar-monitor:
    build: ./radar_proyecto
    container_name: radar_monitor
    network_mode: "host"
    restart: always
    # --- LÍNEAS CRÍTICAS PARA VIDEO ROBUSTO ---
    shm_size: '512mb' # Evita que FFmpeg se bloquee por falta de memoria RAM compartida
    volumes:
      - /mnt/darat:/mnt/darat
      - /dev/shm:/dev/shm # Permite que el host vea los buffers de 15s creados en RAM
    # ------------------------------------------
    command: python3 app/monitor_radar.py

  # 2. EL BOT (Comandos y alertas)
  radar-bot:
    build: ./radar_proyecto
    container_name: radar_bot
    network_mode: "host"
    restart: always
    environment:
      - URL_PUBLICO=https://radar.radar-lcc.site
    volumes:
      - /mnt/darat:/mnt/darat
    command: python3 app/bot_comando.py

  # 3. EL TÚNEL (Cloudflare)
  radar-tunel:
    image: cloudflare/cloudflared:latest
    container_name: radar_tunel_fijo
    network_mode: "host"
    restart: always
    environment:
      - TUNNEL_TOKEN=eyJhIjoiMDk0YmJhYzIzMTBjNTRhMWJhNjcwN2ZlYjNkNjM2MzAiLCJ0IjoiNTk4NDcxMGEtOGUxYS00ZWE4LTg4MjAtNDk5NTIwMGQ3ZjFlIiwicyI6Ik56TTJaV1F5TmpVdE5Ea3pNaTAwTWpRd0xXRm1ORGN0TkdGaE5USTJOelU0Tm1ZMCJ9
    command: tunnel --no-autoupdate run --url http://127.0.0.1:8085

  # 4. EL DASHBOARD (Web)
  radar-dashboard:
    build: ./radar_web
    container_name: radar_dashboard
    restart: always
    ports:
      - "8085:8501"
    volumes:
      - /mnt/darat/data:/app/data_folder
      - /mnt/darat/clips:/app/clips:ro
      - /mnt/darat/multas_fotos:/app/imagenes_multas
      - ./radar_web/pages:/app/pages
      - ./radar_web/.streamlit:/app/.streamlit:ro
      - /mnt/darat:/mnt/darat