version: '3.8'

services:
  radar_dashboard:
    build: .
    container_name: radar_dashboard
    ports:
      - "8085:8501"
    environment:
      - TZ=America/Mexico_City
    volumes:
      # Conectamos a la base de datos en el disco de 900GB
      - /mnt/darat/data:/app/data_folder
      
      # Conectamos a los clips de video (solo lectura)
      - /mnt/darat/clips:/app/clips:ro
      
      # Configuración de la interfaz
      - ./.streamlit:/app/.streamlit:ro
      
      # Carpeta de las páginas (donde vive Infracciones_Graves.py)
      - ./pages:/app/pages
      
      # Mapeo antiguo (Lo mantenemos por si acaso usas 'imagenes_multas' en otro lado)
      - /mnt/darat/multas_fotos:/app/imagenes_multas

      # --- NUEVA LÍNEA NECESARIA ---
      # Esto permite que el dashboard encuentre la ruta '/mnt/darat/multas_fotos/'
      - /mnt/darat:/mnt/darat

    restart: always